//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlibKey.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OlibKey.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456
        ///123456789
        ///111111
        ///1234567
        ///666666
        ///12345678
        ///7777777
        ///123321
        ///0
        ///654321
        ///1234567890
        ///123123
        ///555555
        ///vkontakte
        ///gfhjkm
        ///159753
        ///777777
        ///TempPassWord
        ///qwerty
        ///qazwsx
        ///1q2w3e
        ///1234
        ///112233
        ///121212
        ///qwertyuiop
        ///qq18ww899
        ///987654321
        ///12345
        ///zxcvbn
        ///zxcvbnm
        ///999999
        ///samsung
        ///ghbdtn
        ///1q2w3e4r
        ///1111111
        ///123654
        ///159357
        ///131313
        ///qazwsxedc
        ///123qwe
        ///222222
        ///asdfgh
        ///333333
        ///9379992
        ///asdfghjkl
        ///4815162342
        ///12344321
        ///любовь
        ///88888888
        ///11111111
        ///knopka
        ///789456
        ///qwertyu
        ///1q2w3e4r5t
        ///iloveyou
        ///vfhbyf
        ///marina
        ///passw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BadPasswords {
            get {
                return ResourceManager.GetString("BadPasswords", resourceCulture);
            }
        }
    }
}
